apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - api-gateway.yaml
  - auth-accounts.yaml
  - boards-threads-posts.yaml
  - media-uploads.yaml
  - search-indexing.yaml
  - moderation-anti-spam.yaml
